# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1
  - nightly
notifications:
  email: false

codecov: true
coveralls: true

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - stage: Documentation
      julia: 0.1
      script: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
